schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"
  types:
    EnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        table_name:
          type: string
          description: "Shared Dynamo DB table name"
          default: myDynamoDbTable
          minLength: 3
          maxLength: 30
        api_name:
          type: string
          description: "Shared API Gateway name"
          default: myApi
          minLength: 3
          maxLength: 30
        stage_name:
          type: string
          description: "API Gateway stage name"
          default: stage
          minLength: 3
          maxLength: 30
        lambda_alias_name:
          type: string
          description: "Lambda Alias name"
          default: stage
        healthcheck_function_name:
          type: string
          description: "Lambda Health Check function name"
          minLength: 3
          maxLength: 30
        healthcheck_function_handler:
          type: string
          description: "Lambda Health Check function handler"
        healthcheck_function_runtime:
          type: string
          description: "The runtime for Health Check function"
          enum: [ "nodejs12.x", "nodejs14.x", "python3.8", "ruby2.7", "java11", "java8", "go1.x", "dotnetcore3.1" ]
          default: "nodejs14.x"
        healthcheck_function_code_uri:
          type: string
          description: "The s3 link to Health Check function code"
          minLength: 5
          maxLength: 200
